[package]
name = "genpwd"
version = "1.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
clap = "4"
toml = "0.8"
serde = "1.0"

[dependencies.qr_code]
version = "2.0.0"
optional = true
features = ["bmp"]

[dependencies.sdl2]
version = "0.37.0"
optional = true
features = ["image"]

# TODO: solve how to conditionally download/compile dep crates
[features]
default = ["qr_code", "sdl2"] 
